# Generated by Django 2.2.24 on 2022-12-23 09:25

from django.db import migrations


def populate_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building=True
        else:
            flat.new_building=False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(populate_new_building),
    ]
