# Generated by Django 2.2.24 on 2022-12-23 09:25

from django.db import migrations


def populate_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    flats = Flat.objects.filter(construction_year__gt=2014).update(new_building=True)
    flats = Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(populate_new_building),
    ]
