# Generated by Django 2.2.24 on 2022-12-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20221223_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to='property.Flat', verbose_name='Кто лайкнул'),
        ),
    ]
