# Generated by Django 2.2.24 on 2022-12-23 18:42

from django.db import migrations
import phonenumbers

def populate_normalized_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        normalized_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(normalized_phonenumber):
            flat.pure_phonenumber = f"+{normalized_phonenumber.country_code}{normalized_phonenumber.national_number}"
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_pure_phonenumber'),
    ]

    operations = [
        migrations.RunPython(populate_normalized_numbers)
    ]
