# Generated by Django 2.2.24 on 2022-12-23 21:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221223_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца?')),
                ('owner_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца:')),
                ('owner_normalized_phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца:')),
                ('ownership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats_owner', to='property.Flat', verbose_name='Квартиры в собственности:')),
            ],
        ),
    ]
