# Generated by Django 2.2.24 on 2022-12-23 21:54

from django.db import migrations
from itertools import chain

def populate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats = Flat.objects.all()
    flats_iterator = flats.iterator()
    try:
        flat_one = next(flats_iterator)
    except StopIteration:
        pass
    else:
        for flat in chain([flat_one], flats_iterator):
            owner, created = Owner.objects.get_or_create(
                    name=flat.owner,
                    phonenumber=flat.owners_phonenumber,
                    defaults={
                        'name': flat.owner,
                        'phonenumber': flat.owners_phonenumber,
                        'pure_phonenumber': flat.pure_phonenumber
                    }
            )
            flat.owners.set([owner])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(populate_owners)
    ]
