# Generated by Django 2.2.24 on 2022-12-23 21:54

from django.db import migrations
from property.models import Flat, Complaint, Owner
import phonenumbers

def populate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats.iterator():
        owner, created = Owner.objects.update_or_create(
                name = flat.owner,
                owner_phonenumber=flat.owners_phonenumber,
                owner_normalized_phonenumber=flat.pure_phonenumber
                defaults={
                    'name': flat.owner,
                    'owners_phonenumber': flat.owners_phonenumber,
                    'owner_normalized_phonenumber': flat.pure_phonenumber}
        )
        owner.save()


def populate_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in flats.iterator():
        object, created = Owner.objects.update_or_create(
            owner=flat.owner,
            owner_phonenumber=flat.owners_phonenumber,
            owner_normalized_phonenumber=flat.pure_phonenumber,
            )
        if created:
            object.owners.set(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(populate_owners, populate_flats)
    ]
