# Generated by Django 2.2.24 on 2022-12-23 21:54

from django.db import migrations


def populate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_phonenumber=flat.owners_phonenumber,
            owner_normalized_phonenumber=flat.pure_phonenumber,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(populate_owners)
    ]
